input.onGesture(Gesture.Shake, function () {
    basic.showString("C")
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.setLedColors(0xb09eff, 0x00ffff, 0x007fff)
    basic.pause(1000)
})
input.onPinTouchEvent(TouchPin.P1, input.buttonEventDown(), function () {
    basic.showString("D")
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.setLedColors(0xff9da5, 0x00ff00, 0xb09eff)
    basic.pause(1000)
})
input.onButtonEvent(Button.A, input.buttonEventClick(), function () {
    basic.showString("A")
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.setLedColors(0x000000, 0xff0000, 0xff8000)
    basic.pause(1000)
})
input.onPinTouchEvent(TouchPin.P2, input.buttonEventDown(), function () {
    basic.showString("E")
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.setLedColors(0x00ffff, 0x007fff, 0x65471f)
    basic.pause(1000)
})
input.onPinTouchEvent(TouchPin.P0, input.buttonEventDown(), function () {
    basic.showString("C")
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.setLedColors(0xff0000, 0xff8000, 0xffff00)
    basic.pause(1000)
})
input.onButtonEvent(Button.AB, input.buttonEventClick(), function () {
    basic.showString("G")
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.setLedColors(0xff00ff, 0xffffff, 0x999999)
    basic.pause(1000)
})
input.onButtonEvent(Button.B, input.buttonEventClick(), function () {
    basic.showString("B")
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.setLedColors(0xffff00, 0xff9da5, 0x00ff00)
    basic.pause(1000)
})
input.onPinTouchEvent(TouchPin.P3, input.buttonEventDown(), function () {
    basic.showString("F")
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.setLedColors(0x0000ff, 0x7f00ff, 0xff0080)
    basic.pause(1000)
})
input.onGesture(Gesture.FreeFall, function () {
    basic.showString("D")
    music.playTone(587, music.beat(BeatFraction.Whole))
    basic.setLedColors(0x65471f, 0x0000ff, 0x7f00ff)
    basic.pause(1000)
})
basic.showIcon(IconNames.ArrowWest)
basic.showIcon(IconNames.ArrowSouthWest)
basic.showIcon(IconNames.ArrowSouthEast)
basic.showIcon(IconNames.ArrowEast)
